<a href="https://colab.research.google.com/github/Francesca2020-eng/Linear-Algebra-58020/blob/main/Applications_of_Linear_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Systems of Linear Equation can be solved with arrays and Numpy

In [8]:
import numpy as np
from scipy.linalg import solve

A = np.array([[4,5],[3,-2]])
print(A)

B = np.array([[7],[11]])
print(B)

inv_A = np.linalg.inv(A)
print(inv_A)

X = np.linalg.inv(A).dot(B)
print(X)

[[ 4  5]
 [ 3 -2]]
[[ 7]
 [11]]
[[ 0.08695652  0.2173913 ]
 [ 0.13043478 -0.17391304]]
[[ 3.]
 [-1.]]


In [9]:
inv_A = np.linalg.inv(A)
print(inv_A)

X = np.dot(inv_A,B)
print(X)


[[ 0.08695652  0.2173913 ]
 [ 0.13043478 -0.17391304]]
[[ 3.]
 [-1.]]


In [10]:
X = np.linalg.solve(A,B)
print(X)


[[ 3.]
 [-1.]]


In [11]:
from scipy.linalg import solve

X = solve(A,B)
print(X)

[[ 3.]
 [-1.]]
