<a href="https://colab.research.google.com/github/Francesca2020-eng/Linear-Algebra-58020/blob/main/Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and its Operations

In [15]:
import numpy as np
#create a 2 x 2 array
A = np.array([[-5,0,],[4,1]])
print (A)


[[-5  0]
 [ 4  1]]


In [14]:
B = np.array([[6,-3],[2,3]])
print (B)

[[ 6 -3]
 [ 2  3]]


In [11]:
#sum = A + B
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print (A+B)

[[ 1 -3]
 [ 6  4]]


In [12]:
#difference 1 = A - B
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print (A-B)

[[-11   3]
 [  2  -2]]


In [13]:
#difference 2 = B - B
B = np.array([[6,-3],[2,3]])
print (B-B)

[[0 0]
 [0 0]]
