<a href="https://colab.research.google.com/github/Francesca2020-eng/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1 #Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have?

In [5]:
import numpy as np

EQ1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
EQ2 = np.array([[89],[89],[95]])
amt = np.linalg.inv(EQ1).dot(EQ2)
print(amt)

[[13.]
 [57.]
 [19.]]


Q2 #Solve each system: 

In [4]:
import numpy as np
from scipy.linalg import solve

A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)

B = np.array ([[5],[15],[-20]])
print (B)

inv_A = np.linalg.inv(A)
print(inv_A)

X = np.linalg.inv(A).dot(B)
print (X)

#Explanation:
# because the determinant is single matrix so that the given matrix does not have an inverse.
#Singular matrix is non-invertible.

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]


LinAlgError: ignored

Q3 #Consider the matrix,

In [2]:
#Find the eigenvalue/s
#Find the eigenvectors

import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print (A)

w,v = np.linalg.eig(A)
print("The eigenvalues is/are",w)
print("The right eigenvectors are",v)

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalues is/are [-1.  3.  2.]
The right eigenvectors are [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
