<a href="https://colab.research.google.com/github/Francesca2020-eng/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Python program to inverse and transpose.

In [9]:
##python program to inverse a 3x3 Matrix A=([5,4,2],[6,-3,-5],[3,5,9])
A=np.array([[5,4,2],[6,-3,-5],[3,5,9]])
invA=(np.linalg.inv(A))
print(invA)

[[ 0.00961538  0.125       0.06730769]
 [ 0.33173077 -0.1875     -0.17788462]
 [-0.1875      0.0625      0.1875    ]]


In [10]:
##python program to transpose a 3x3 Matrix A=([5,4,2],[6,-3,-5],[3,5,9])
A=np.array([[5,4,2],[6,-3,-5],[3,5,9]])
print(A)

B=np.transpose(A)
print(B)

[[ 5  4  2]
 [ 6 -3 -5]
 [ 3  5  9]]
[[ 5  6  3]
 [ 4 -3  5]
 [ 2 -5  9]]
