<a href="https://colab.research.google.com/github/Francesca2020-eng/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. Consider the four matrices


A. WY

In [27]:
import numpy as np
W = np.array ([[1,-3],[2,-2],[3,1]])
Y = np.array ([[1,2,0],[0,-1,2]])

print(np.dot(W,Y))


[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


B. Z+Z


In [7]:
#Addition of matrices
Z = np.array ([[0,1],[2,3]])
print (Z+Z)

[[0 2]
 [4 6]]


C. 3X

In [31]:
X = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])
output = np.dot(3,X)
print (output)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


Problem 2


A. The product (YW)2 is not defined


In [34]:
W = np.array ([[1,-3],[2,-2],[3,1]])
Y = np.array ([[1,2,0],[0,-1,2]])
 
S = np.dot(Y,W)
print (S*S)
#Statement is not true

[[25 49]
 [16 16]]


B. WY-X

In [38]:
W = np.array ([[1,-3],[2,-2],[3,1]])
Y = np.array ([[1,2,0],[0,-1,2]])
X = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])

S = np.dot(W,Y)

print(np.subtract(S,X))

#Statement is true

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


C.  YW – Z^2 =

In [42]:
W = np.array ([[1,-3],[2,-2],[3,1]])
Y = np.array ([[1,2,0],[0,-1,2]])
Z = np.array ([[0,1],[2,3]])

S = np.dot(Y,W)
R = Z*Z
print(np.subtract(S,R))

#Statement is not true


[[ 5 -8]
 [ 0 -5]]
