<a href="https://colab.research.google.com/github/Francesca2020-eng/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [22]:
#create a 4 x 4 matrix
import numpy as np
C=  np.array([1,1,1,1])

print(np.diag(C))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Question 2

In [18]:
#doubles all the values of each element
C = np.array ([1,1,1,1])

D = np.diag(C)
print(np.multiply(D,D))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Question 3

In [7]:
#initialize arrays
A = np.array([2,7,4])
B = np.array([3,9,8])

#compute for the cross product
output = np.cross(A,B)
print(output)

[20 -4 -3]
