<a href="https://colab.research.google.com/github/Francesca2020-eng/Linear-Algebra-58020/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#LINEAR TRANSFORMATION
import numpy as np
A = np.array([[1,1,1],[1,2,2],[1,2,3]])
print(A)
inverse_A=np.linalg.inv(A)
print(inverse_A)

B = np.array([[5],[6],[8]])
print(B)

#AA^-1x = B.A^-1
X = np.dot(inverse_A,B)
print(X)

[[1 1 1]
 [1 2 2]
 [1 2 3]]
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]
[[5]
 [6]
 [8]]
[[ 4.]
 [-1.]
 [ 2.]]
