<a href="https://colab.research.google.com/github/Francesca2020-eng/Linear-Algebra-58020/blob/main/Vector_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and its Operations

In [1]:
import numpy as np 
#create a 1x3 array
a= np.array([1,2,3])
print (a)

[1 2 3]


In [2]:
# create a 2 x 3 matrix
b = np.array([[1,2,3],[4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [3]:
#create a 3 x 3 matriz
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#create a constant array with all values are 6 
d = np.full ((4,4),6) # This is an example of square matrix
print (d)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [7]:
#create a diagonal matrix
e = np.array  ([[1,2,3],[4,5,6],[7,8,9]]) 
print (e)
e = np.diagonal ([[1,2,3],[4,5,6],[7,8,9]]) 
print (e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [8]:
#create an identity matrix 
f = np.eye(4)
print (f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
#create a zero matrix
g = np.zeros ((6,5))
print  (g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#create an empty matrix
h = np.empty ((0,5))
print (h)

[]


In [25]:
#Addition of matrix
i = np.array([[1,2,3],[4,5,6]])
j = np.zeros((2,3))
print (i+j)

[[1. 2. 3.]
 [4. 5. 6.]]


In [19]:
#subtraction of matrices
i = np.array([[1,2,3],[4,5,6]])
j = np.array([[-1,2,4],[7,4,2]])
print (i)
print (j)

[[1 2 3]
 [4 5 6]]
[[-1  2  4]
 [ 7  4  2]]


In [21]:
#Subtraction of Matrices 
i = np.array([[1,2,3],[4,5,6]])
j = np.array([[-1,2,4],[7,4,2]])
print (i-j)

[[ 2  0 -1]
 [-3  1  4]]
